chore: 🩹👷‍♂️ update workflows[#19]

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Docker Compose Build and Deploy
+name: Docker Build and Deploy
 
 on:
   push:
@@ -9,28 +9,35 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Code
+      - name: checkout
         uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
+      - name: install java 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: 'zulu'
+
+      - name: assign grant gradlew
+        run: chmod +x gradlew
+
+      - name: bootJar with gradle
+        run: ./gradlew bootJar -x test
+
+      - name: set up docker buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Set up Docker Compose
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y docker-compose
-
-      - name: Log in to Docker Hub
+      - name: login to docker hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Build and Push with Docker Compose
+      - name: Push Docker Image
         run: |
-          docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKERHUB_USERNAME }}"/coffeetime --push .
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/coffeetime:latest
 
-      - name: Deploy to EC2
+      - name: deploy to ec2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -38,20 +45,19 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             cd /home/ubuntu/
-
             sudo rm -f .env
             sudo rm -f docker-compose.yml
-
+            
             sudo touch .env
             echo "${{ secrets.ENV_VARS }}" | sudo tee .env > /dev/null
-
+            
             sudo touch docker-compose.yml
             echo "${{ secrets.DOCKER_COMPOSE }}" | sudo tee docker-compose.yml > /dev/null
-
+            
             sudo chmod 666 /var/run/docker.sock
-
             sudo docker rm -f $(docker ps -qa)
-            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-            docker pull changedan/coffeetime || exit 1  # Exit if pull fails
+
+            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+            docker pull "${{ secrets.DOCKERHUB_USERNAME }}"/coffeetime || exit 1  # Exit if pull fails
             docker-compose -f docker-compose.yml --env-file ./.env up -d || exit 1
             docker image prune -f
