chore: 🩹👷‍♂️ update workflows[#19]

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,16 +15,20 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Log in to Docker Hub using CLI
-        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
-
-      - name: Build with Docker Compose
+      - name: Set up Docker Compose
         run: |
-          docker-compose build --no-cache
+          sudo apt-get update
+          sudo apt-get install -y docker-compose
 
-      - name: Push Docker Image
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+      - name: Build and Push with Docker Compose
         run: |
-          docker-compose push "${{ secrets.DOCKERHUB_USERNAME }}"/coffeetime:latest
+          docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKERHUB_USERNAME }}"/coffeetime --push .
 
       - name: Deploy to EC2
         uses: appleboy/ssh-action@master
@@ -44,20 +48,10 @@ jobs:
             sudo touch docker-compose.yml
             echo "${{ secrets.DOCKER_COMPOSE }}" | sudo tee docker-compose.yml > /dev/null
 
-            # Set correct permissions for Docker socket
             sudo chmod 666 /var/run/docker.sock
 
-            # Log in to Docker Hub from EC2
-            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
-
-            # Remove any running Docker containers
             sudo docker rm -f $(docker ps -qa)
-
-            # Pull the latest image from Docker Hub
-            sudo docker pull "${{ secrets.DOCKERHUB_USERNAME }}"/coffeetime:latest || exit 1
-
-            # Run containers using docker-compose
-            sudo docker-compose -f docker-compose.yml --env-file ./.env up -d || exit 1
-
-            # Clean up old Docker images
-            sudo docker image prune -f
+            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+            docker pull changedan/coffeetime || exit 1  # Exit if pull fails
+            docker-compose -f docker-compose.yml --env-file ./.env up -d || exit 1
+            docker image prune -f
